## Creating Arrays

In [4]:
# Creating Numpy arrays
import numpy as np

# Converting from a list
#Lets start with a list

my_list1 = [1,2,3,5]

my_array1 = np.array(my_list1)

In [2]:
#Print out array
my_array1

array([1, 2, 3, 5])

In [9]:
# Make another list
my_list2 = [11,22,33,0]

In [10]:
#Make a list of lists
my_lists = [my_list1,my_list2]
my_lists

[[1, 2, 3, 4], [11, 22, 33, 0]]

In [11]:
#Make multi-dimensional array
my_array2 = np.array(my_lists)

#Show array
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33,  0]])

In [12]:
#Lets get the size of the array
my_array2.shape

(2, 4)

In [13]:
#Find out the data tyoe of the array
my_array2.dtype

dtype('int64')

In [16]:
#Zeros
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
#Ones
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
# An empty array

np.empty(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.empty((3,4))

array([[1.75631032e-152, 1.71387289e+214, 6.22651684e+228,
        1.23537790e+171],
       [5.98162278e-154, 6.01347002e-154, 7.30654970e+281,
        8.78381893e+247],
       [2.02822726e-110, 6.01347002e-154, 5.50409548e+257,
        6.01347002e-154]])

In [20]:
#Identity array
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
# Using a range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.array([range(10,2,-2),range(2,10,2)])

array([[10,  8,  6,  4],
       [ 2,  4,  6,  8]])

## Using Arrays

In [39]:
# Create array
arr1 = np.array([[1,2,3],[8,9,10]])
arr2 = np.array([[1,2,4],[8,9,11]])
arr1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [40]:
#Multiplying Arrays
arr1*arr2

array([[  1,   4,  12],
       [ 64,  81, 110]])

In [41]:
#Subtraction
arr1-arr2

array([[ 0,  0, -1],
       [ 0,  0, -1]])

In [42]:
#Arithmetic operations with scalars on array
1 / arr1

array([[1.        , 0.5       , 0.33333333],
       [0.125     , 0.11111111, 0.1       ]])

In [44]:
#Exponential operation
arr4 = arr1 ** 3
arr4

array([[   1,    8,   27],
       [ 512,  729, 1000]])

## Indexing Arrays

In [45]:
#Creating sample array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
#Get values in a range
arr[0:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [53]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100.25
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [54]:
#Slices
slice_of_arr = arr[0:6]
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [55]:
#Change Slice
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [56]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [57]:
#To get a copy
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [63]:
# Indexing a 2D array
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [64]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [66]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][2]

30

In [69]:
# Getting individual element value
arr_2d[:,1]

array([10, 25, 40])

In [70]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[0:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

## Operations

In [92]:
np.random.seed(102) 
arr = np.random.randint(0,100,15)
arr

array([ 0, 78, 66, 73, 72, 45, 72, 73, 79,  7,  4, 38, 82, 55,  3])

In [98]:
np.random.seed(1) 
arr2 = np.random.randint(0,100,10)
arr2

array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1])

In [99]:
arr.max()

82

In [100]:
arr.min()

0

In [101]:
arr.mean()

49.8

In [102]:
arr.argmin()

0

In [103]:
arr.argmax()

12

In [104]:
arr.shape

(15,)

In [109]:
arr = arr.reshape(3,5)

In [110]:
arr

array([[ 0, 78, 66, 73, 72],
       [45, 72, 73, 79,  7],
       [ 4, 38, 82, 55,  3]])

## Array Transposition

In [111]:
#Create array
arr = np.arange(50).reshape((10,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [112]:
#Lets transpose
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [113]:
# Taking dot product of matrices
np.dot(arr.T,arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [114]:
# For 3D matrix
arr3d = np.arange(50).reshape((5,5,2))
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [122]:
# Transpose a 3d matrix
arr3d.transpose((1,2,0))

array([[[ 0, 10, 20, 30, 40],
        [ 1, 11, 21, 31, 41]],

       [[ 2, 12, 22, 32, 42],
        [ 3, 13, 23, 33, 43]],

       [[ 4, 14, 24, 34, 44],
        [ 5, 15, 25, 35, 45]],

       [[ 6, 16, 26, 36, 46],
        [ 7, 17, 27, 37, 47]],

       [[ 8, 18, 28, 38, 48],
        [ 9, 19, 29, 39, 49]]])

In [126]:
# Swapaxes
arr = np.array([[1,2,3]])
arr

array([[1, 2, 3]])

In [131]:
arr.shape

(1, 3)

In [134]:
arr = arr.swapaxes(1,0)
arr

array([[1],
       [2],
       [3]])

## Universal Array Functions

In [135]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [136]:
# Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [137]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [140]:
# Binary Functions require two arrays

#Random array (normal dist)
A = np.random.randn(10)
A

array([-0.3224172 , -0.38405435,  1.13376944, -1.09989127, -0.17242821,
       -0.87785842,  0.04221375,  0.58281521, -1.10061918,  1.14472371])

In [141]:
#Random array (normal dist)
B = np.random.randn(10)
B

array([ 0.90159072,  0.50249434,  0.90085595, -0.68372786, -0.12289023,
       -0.93576943, -0.26788808,  0.53035547, -0.69166075, -0.39675353])

In [143]:
#Addition
np.add(A,B)
np.multiply(A,B)

array([-0.29068836, -0.19298514,  1.02136295,  0.7520263 ,  0.02118974,
        0.82147308, -0.01130856,  0.30909923,  0.76125509, -0.45417317])

In [144]:
#Finding max or min between two arrays
np.maximum(A,B)

array([ 0.90159072,  0.50249434,  1.13376944, -0.68372786, -0.12289023,
       -0.87785842,  0.04221375,  0.58281521, -0.69166075,  1.14472371])

## Array Processing

In [157]:
#Set array 
points = np.arange(0,100,1)

In [146]:
points.shape

(1000,)

In [153]:
#np.random.seed(100)
points = np.linspace(0,100,100)
points

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

In [158]:
#Create the grid
dx,dy=np.meshgrid(points,points)

In [160]:
points

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [159]:
dx

array([[ 0,  1,  2, ..., 97, 98, 99],
       [ 0,  1,  2, ..., 97, 98, 99],
       [ 0,  1,  2, ..., 97, 98, 99],
       ...,
       [ 0,  1,  2, ..., 97, 98, 99],
       [ 0,  1,  2, ..., 97, 98, 99],
       [ 0,  1,  2, ..., 97, 98, 99]])

In [161]:
dy

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 1,  1,  1, ...,  1,  1,  1],
       [ 2,  2,  2, ...,  2,  2,  2],
       ...,
       [97, 97, 97, ..., 97, 97, 97],
       [98, 98, 98, ..., 98, 98, 98],
       [99, 99, 99, ..., 99, 99, 99]])

In [162]:
# Evaluating Function
z = (np.sin(dx) + np.sin(dy))
z

array([[ 0.        ,  0.84147098,  0.90929743, ...,  0.37960774,
        -0.57338187, -0.99920683],
       [ 0.84147098,  1.68294197,  1.75076841, ...,  1.22107872,
         0.26808911, -0.15773585],
       [ 0.90929743,  1.75076841,  1.81859485, ...,  1.28890517,
         0.33591555, -0.08990941],
       ...,
       [ 0.37960774,  1.22107872,  1.28890517, ...,  0.75921548,
        -0.19377413, -0.6195991 ],
       [-0.57338187,  0.26808911,  0.33591555, ..., -0.19377413,
        -1.14676374, -1.57258871],
       [-0.99920683, -0.15773585, -0.08990941, ..., -0.6195991 ,
        -1.57258871, -1.99841367]])

In [168]:
A = np.array([1,2,3,4])

B= np.array([100,200,300,400])

# Boolean array
condition = np.array([True,True,False,False])

#Using a list comprehension
answer = [(A_val if cond else B_val) for A_val,B_val,cond in zip(A,B,condition)]
answer

[1, 2, 300, 400]

In [169]:
# Using numpy.where

answer2 = np.where(condition,A,B)
answer2

array([  1,   2, 300, 400])

In [170]:
# Use np.where  on 2d for manipulation

from numpy.random import randn
arr = randn(5,5)
arr

array([[-0.6871727 , -0.84520564, -0.67124613, -0.0126646 , -1.11731035],
       [ 0.2344157 ,  1.65980218,  0.74204416, -0.19183555, -0.88762896],
       [-0.74715829,  1.6924546 ,  0.05080775, -0.63699565,  0.19091548],
       [ 2.10025514,  0.12015895,  0.61720311,  0.30017032, -0.35224985],
       [-1.1425182 , -0.34934272, -0.20889423,  0.58662319,  0.83898341]])

In [171]:
# Where array is less than zero, make that value zero, otherwise leave it as the array value
np.where(arr < 0,0,arr)

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.2344157 , 1.65980218, 0.74204416, 0.        , 0.        ],
       [0.        , 1.6924546 , 0.05080775, 0.        , 0.19091548],
       [2.10025514, 0.12015895, 0.61720311, 0.30017032, 0.        ],
       [0.        , 0.        , 0.        , 0.58662319, 0.83898341]])

In [172]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [175]:
# SUM
arr.sum(axis=1)

array([ 6, 15, 24])

In [176]:
# Sum along an axis
arr.sum(0)

array([12, 15, 18])

In [177]:
#Mean
arr.mean()

5.0

In [178]:
#Standard Deviation
arr.std()

2.581988897471611

In [179]:
#Variance
arr.var()

6.666666666666667

In [180]:
# Sort array
arr = randn(5)
arr

array([ 0.93110208,  0.28558733,  0.88514116, -0.75439794,  1.25286816])

In [181]:
arr.sort()
arr

array([-0.75439794,  0.28558733,  0.88514116,  0.93110208,  1.25286816])

In [182]:
# Unique values
countries = np.array(['France', 'Germany', 'USA', 'Russia','USA','Mexico','Germany'])
np.unique(countries)

array(['France', 'Germany', 'Mexico', 'Russia', 'USA'], dtype='<U7')

In [183]:
# in1d test values in one array
np.in1d(['France','USA','Sweden'],countries)

array([ True,  True, False])

## Masking

In [184]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [185]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [187]:
len(mat[(mat>50) & (mat<70)])

19