## Creation

In [2]:
import numpy as np
#from pandas import Series, DataFrame
import pandas as pd
from numpy.random import randn

### Series

In [97]:
#Lets create a new series
ser1 = pd.Series([1,2,3,4])
ser1

0    1
1    2
2    3
3    4
dtype: int64

In [98]:
#Lets create a new series
ser1 = pd.Series([1,2,3,4],index=['A','B','C','D'])
ser1

A    1
B    2
C    3
D    4
dtype: int64

#### Series Reindexing

In [110]:
#Call reindex to rearrange the data to a new index
ser2 = ser1.reindex(['A','B','C','D','E','F'])
ser2

A    1.0
B    2.0
C    3.0
D    4.0
E    NaN
F    NaN
dtype: float64

In [111]:
# We can alos fill in values for new indexes
ser2.reindex(['B','A','Sachin','D','E','F','C'],fill_value=0)

B         2.0
A         1.0
Sachin    0.0
D         4.0
E         NaN
F         NaN
C         3.0
dtype: float64

In [112]:
ser2

A    1.0
B    2.0
C    3.0
D    4.0
E    NaN
F    NaN
dtype: float64

In [113]:
#Using a particular method for filling values
ser3 = pd.Series([0,5,10],index=[0,5,10])
ser3

0      0
5      5
10    10
dtype: int64

In [11]:
#Forward fill for interploating values vetween indices 
ser3.reindex(range(15),method='ffill')

0      0
1      0
2      0
3      0
4      0
5      5
6      5
7      5
8      5
9      5
10    10
11    10
12    10
13    10
14    10
dtype: int64

### Data frame

In [1]:
#using np array

data=np.array([[100,92,83],[94,85,86]])

data

array([[100,  92,  83],
       [ 94,  85,  86]])

In [2]:
data.shape

(2, 3)

In [3]:
type(data)

numpy.ndarray

In [6]:
df2=pd.DataFrame(data)

df2

0   1   2
0  100  92  83
1   94  85  86

In [117]:
df1=pd.DataFrame(data,index=['Priyanka','Rahul'],columns=['math','physics','English'])

df1

math  physics  English
Priyanka   100       92       83
Rahul       94       85       86

In [119]:
randn(25)

array([-0.2491533 , -0.18149499, -0.47343577, -2.09987634, -0.61880379,
       -1.44292101, -0.73644066,  1.71769283,  0.64471379, -1.51469502,
       -0.3788882 ,  0.27612822, -2.28752715,  1.40973092,  0.99746998,
        0.45889302,  0.52333171,  0.68210476, -0.91422903, -1.35823824,
       -1.57116541, -0.15180097, -0.57319063,  0.13672322, -0.62502198])

In [124]:
#s1=pd.Series(randn(25))
randn(25).reshape((5,5))

array([[-1.42875625, -1.32034974,  1.50477327, -0.4428814 , -0.45818243],
       [-1.5885295 ,  0.23624058,  0.54439819,  0.6469662 , -1.41654404],
       [-1.30708359, -1.33093498,  0.40060994, -0.47877131,  2.15431319],
       [ 1.35458975,  1.20279767,  0.57268625,  0.67920117, -1.08062519],
       [ 1.19458173,  0.48216285, -0.2535928 , -1.46066885, -0.92087806]])

In [125]:
#Reindexing rows, columns or both

#Lets make a dataframe with some random values
df = pd.DataFrame(randn(25).reshape((5,5)),
               index=['A','B','D','E','F'],
               columns=['col1','col2','col3','col4','col5'])
df

col1      col2      col3      col4      col5
A -0.268201  0.928831 -0.999566 -0.620251 -0.732686
B -0.355372  0.569031  0.477877  0.595954 -1.320820
D -0.605124 -0.689018 -0.201476 -0.987271 -1.710806
E  0.974854 -0.352300 -0.987143 -0.031912  0.645428
F -0.198561 -1.639928 -0.965239  1.091047  1.284188

In [126]:
#Notice we forgot 'C' , lets reindex it into df
df2 = df.reindex(['A','B','C','D','E','F'])
df2

col1      col2      col3      col4      col5
A -0.268201  0.928831 -0.999566 -0.620251 -0.732686
B -0.355372  0.569031  0.477877  0.595954 -1.320820
C       NaN       NaN       NaN       NaN       NaN
D -0.605124 -0.689018 -0.201476 -0.987271 -1.710806
E  0.974854 -0.352300 -0.987143 -0.031912  0.645428
F -0.198561 -1.639928 -0.965239  1.091047  1.284188

In [127]:
#Can also explicitly reindex columns
new_columns = ['col1','col2','col3','col4','col5','col6']
df2.reindex(columns=new_columns)

col1      col2      col3      col4      col5  col6
A -0.268201  0.928831 -0.999566 -0.620251 -0.732686   NaN
B -0.355372  0.569031  0.477877  0.595954 -1.320820   NaN
C       NaN       NaN       NaN       NaN       NaN   NaN
D -0.605124 -0.689018 -0.201476 -0.987271 -1.710806   NaN
E  0.974854 -0.352300 -0.987143 -0.031912  0.645428   NaN
F -0.198561 -1.639928 -0.965239  1.091047  1.284188   NaN

In [128]:
df2

col1      col2      col3      col4      col5
A -0.268201  0.928831 -0.999566 -0.620251 -0.732686
B -0.355372  0.569031  0.477877  0.595954 -1.320820
C       NaN       NaN       NaN       NaN       NaN
D -0.605124 -0.689018 -0.201476 -0.987271 -1.710806
E  0.974854 -0.352300 -0.987143 -0.031912  0.645428
F -0.198561 -1.639928 -0.965239  1.091047  1.284188

## Drop Entries

In [129]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [130]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [131]:
#DataFrame we can drop values from either axis
df1 = pd.DataFrame(np.arange(9).reshape((3,3)),
                index=['SF','LA','NY'],
                columns=['pop','size','year'])
df1

pop  size  year
SF    0     1     2
LA    3     4     5
NY    6     7     8

In [132]:
#Now dropping a row
df2 = df1.drop('LA')

In [133]:
df2

pop  size  year
SF    0     1     2
NY    6     7     8

In [135]:
df2.drop('NY',inplace=True)

In [136]:
df2

pop  size  year
SF    0     1     2

In [134]:
df1

pop  size  year
SF    0     1     2
LA    3     4     5
NY    6     7     8

In [137]:
# Drop a column by specifying that axis is 1
df1.drop(['year','pop'],axis=1)

size
SF     1
LA     4
NY     7

## Selecting Entries

In [7]:
df = pd.DataFrame(np.arange(25).reshape((5,5)),
               index=['NYC','LA','SF','DC','Chi'],
               columns=['A','B','C','D','E'])
df

A   B   C   D   E
NYC   0   1   2   3   4
LA    5   6   7   8   9
SF   10  11  12  13  14
DC   15  16  17  18  19
Chi  20  21  22  23  24

In [8]:
#Select by column name
df['B']

NYC     1
LA      6
SF     11
DC     16
Chi    21
Name: B, dtype: int32

In [9]:
df.B

NYC     1
LA      6
SF     11
DC     16
Chi    21
Name: B, dtype: int32

In [10]:
#Select by multiple columns
df[['B','E']]

B   E
NYC   1   4
LA    6   9
SF   11  14
DC   16  19
Chi  21  24

In [11]:
df

A   B   C   D   E
NYC   0   1   2   3   4
LA    5   6   7   8   9
SF   10  11  12  13  14
DC   15  16  17  18  19
Chi  20  21  22  23  24

In [14]:
# Selection based on boolean responses
df[df['A']<=10] # select * from df where df.a<=10

A   B   C   D   E
NYC   0   1   2   3   4
LA    5   6   7   8   9
SF   10  11  12  13  14

In [12]:
# Boolean response condition
df['C']>8

NYC    False
LA     False
SF      True
DC      True
Chi     True
Name: C, dtype: bool

In [40]:
df['E']<20

NYC     True
LA      True
SF      True
DC      True
Chi    False
Name: E, dtype: bool

In [18]:
df[df.index=='NYC']

A  B  C  D  E
NYC  0  1  2  3  4

In [41]:
# Selection based on boolean responses
df[df['C']>8]

A   B   C   D   E
SF   10  11  12  13  14
DC   15  16  17  18  19
Chi  20  21  22  23  24

In [ ]:
df.iloc['row','col']

In [19]:
df.columns

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [20]:
df

A   B   C   D   E
NYC   0   1   2   3   4
LA    5   6   7   8   9
SF   10  11  12  13  14
DC   15  16  17  18  19
Chi  20  21  22  23  24

In [28]:
df.iloc[[0,3],[3,4]]

D   E
NYC   3   4
DC   18  19

In [15]:
df.iloc[:,[2,3]]

C   D
NYC   2   3
LA    7   8
SF   12  13
DC   17  18
Chi  22  23

In [48]:
df.iloc[[0,2],[2,3]] #by index no

C   D
NYC   2   3
SF   12  13

In [49]:
df.loc[:,['A','B','C']] #by name

A   B   C
NYC   0   1   2
LA    5   6   7
SF   10  11  12
DC   15  16  17
Chi  20  21  22

## Binning

In [29]:
pd.cut(np.array([1, 7, 5, 12, 6, 3]), 3)

[(0.989, 4.667], (4.667, 8.333], (4.667, 8.333], (8.333, 12.0], (4.667, 8.333], (0.989, 4.667]]
Categories (3, interval[float64]): [(0.989, 4.667] < (4.667, 8.333] < (8.333, 12.0]]

In [54]:
pd.cut(np.array([1, 7, 5, 4, 6, 3]), 2)

[(0.994, 4.0], (4.0, 7.0], (4.0, 7.0], (0.994, 4.0], (4.0, 7.0], (0.994, 4.0]]
Categories (2, interval[float64]): [(0.994, 4.0] < (4.0, 7.0]]

In [56]:
pd.cut(np.array([1, 7, 5, 4, 6, 3]), 4)

[(0.994, 2.5], (5.5, 7.0], (4.0, 5.5], (2.5, 4.0], (5.5, 7.0], (2.5, 4.0]]
Categories (4, interval[float64]): [(0.994, 2.5] < (2.5, 4.0] < (4.0, 5.5] < (5.5, 7.0]]

In [38]:
years = [1990,1970,1992,2008,2012,2015,1987,1969,2013,2008,1999,2013]
len(years)

12

In [39]:
decade_bins = [1960,1970,1980,1990,2000,2010,2020] #n-1

In [40]:
decade_cat = pd.cut(years,decade_bins)
len(decade_cat)

12

In [41]:
decade_cat

[(1980, 1990], (1960, 1970], (1990, 2000], (2000, 2010], (2010, 2020], ..., (1960, 1970], (2010, 2020], (2000, 2010], (1990, 2000], (2010, 2020]]
Length: 12
Categories (6, interval[int64]): [(1960, 1970] < (1970, 1980] < (1980, 1990] < (1990, 2000] < (2000, 2010] < (2010, 2020]]

In [36]:
len(decade_cat.categories)

6

In [37]:
pd.value_counts(decade_cat)

(2010, 2020]    4
(1990, 2000]    3
(2000, 2010]    2
(1980, 1990]    2
(1960, 1970]    1
(1970, 1980]    0
dtype: int64

## Concatenate

In [42]:
df1 = pd.DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])
df2 = pd.DataFrame(np.random.randn(3, 3), columns=['Y', 'Q', 'X'])

In [43]:
df1

X         Y         Z
0 -0.504247  0.003640  0.324464
1 -1.090264  1.123340 -0.461440
2  1.113906  0.420234 -0.078023
3 -1.380214 -0.090657 -1.230540

In [44]:
df2

Y         Q         X
0  0.349755  0.742979  0.094949
1 -0.142964 -0.774866 -0.863034
2 -0.497603  1.306882 -0.736350

In [45]:
pd.concat([df1,df2])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN -0.504247  0.003640  0.324464
1       NaN -1.090264  1.123340 -0.461440
2       NaN  1.113906  0.420234 -0.078023
3       NaN -1.380214 -0.090657 -1.230540
0  0.742979  0.094949  0.349755       NaN
1 -0.774866 -0.863034 -0.142964       NaN
2  1.306882 -0.736350 -0.497603       NaN

In [46]:
pd.concat([df1,df2], axis=1)

X         Y         Z         Y         Q         X
0 -0.504247  0.003640  0.324464  0.349755  0.742979  0.094949
1 -1.090264  1.123340 -0.461440 -0.142964 -0.774866 -0.863034
2  1.113906  0.420234 -0.078023 -0.497603  1.306882 -0.736350
3 -1.380214 -0.090657 -1.230540       NaN       NaN       NaN

## Duplicates

In [47]:
df = pd.DataFrame({'key1': ['A'] * 3 + ['B'] * 2 + ['D'] * 1,
                  'key2': [2, 2, 3, 3, 3, 0]})
df

key1  key2
0    A     2
1    A     2
2    A     3
3    B     3
4    B     3
5    D     0

In [48]:
df.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
dtype: bool

In [76]:
df.drop_duplicates()

key1  key2
0    A     2
2    A     3
3    B     3
5    D     0

In [77]:
df

key1  key2
0    A     2
1    A     2
2    A     3
3    B     3
4    B     3
5    D     0

In [78]:
df.drop_duplicates(['key2'])

key1  key2
0    A     2
2    A     3
5    D     0

In [49]:
df.drop_duplicates(['key2'])

key1  key2
0    A     2
2    A     3
5    D     0

In [79]:
list(df.drop_duplicates(['key2']).index)

[0, 2, 5]

In [80]:
# Get non duplicates
df[df.duplicated()]

key1  key2
1    A     2
4    B     3

In [86]:
df.drop_duplicates(['key1'],keep='last')

key1  key2
2    A     3
4    B     3
5    D     0

## Mapping

In [25]:
# DataFrame to work with (Highest elevation cities in USA)
df = pd.DataFrame({'city':['Alma','Brian Head','Fox Park','Pune'],
                    'altitude':[3158,2890,2762,3000]})
df

city  altitude
0        Alma      3158
1  Brian Head      2890
2    Fox Park      2762
3        Pune      3000

In [ ]:
df['Position']=np.where(df['altitude']>=3000,'high','low']

In [26]:
state_map={'Alma':'Colorado','Brian Head':'Utah','Fox Park':'Wyoming'}

In [27]:
df['state'] = df['city'].map(state_map)
df

city  altitude     state
0        Alma      3158  Colorado
1  Brian Head      2890      Utah
2    Fox Park      2762   Wyoming
3        Pune      3000       NaN

In [21]:
df['city'].unique()

array(['Alma', 'Brian Head', 'Fox Park', 'Pune'], dtype=object)

In [28]:
city_encode={'Alma':1, 'Brian Head':2, 'Fox Park':3, 'Pune':4}

In [29]:
df['city']=df['city'].map(city_encode)

In [30]:
df

city  altitude     state
0     1      3158  Colorado
1     2      2890      Utah
2     3      2762   Wyoming
3     4      3000       NaN

In [31]:
def func(x):
    if (x<3000):
        return 'A'
    else:
        return 'B'

In [32]:
df['Alt Class'] = df['altitude'].apply(func)

In [33]:
df

city  altitude     state Alt Class
0     1      3158  Colorado         B
1     2      2890      Utah         A
2     3      2762   Wyoming         A
3     4      3000       NaN         B

In [34]:
df['temp']=np.where(df['altitude']>=3000,'High','Low')

In [35]:
df

city  altitude     state Alt Class  temp
0     1      3158  Colorado         B  High
1     2      2890      Utah         A   Low
2     3      2762   Wyoming         A   Low
3     4      3000       NaN         B  High

In [19]:
df2=df.applymap(func1)

In [20]:
df2

city altitude state
0    B        B     B
1    B        B     B
2    B        B     B
3    B        B     B

In [14]:
type(df2)

pandas.core.series.Series

In [93]:
df

city  altitude     state Alt Class
0        Alma      3158  Colorado         B
1  Brian Head      3000      Utah         B
2    Fox Park      2762   Wyoming         A
3        Pune      3000       NaN         B

## Merge

In [51]:
df1 = pd.DataFrame({'key':['X','Z','Y','Z','X','X'],'data_set_1': np.arange(6)})
df1

key  data_set_1
0   X           0
1   Z           1
2   Y           2
3   Z           3
4   X           4
5   X           5

In [52]:
df2 = pd.DataFrame({'key':['Q','Y','Z'],'data_set_2':[1,2,3]})
df2

key  data_set_2
0   Q           1
1   Y           2
2   Z           3

In [53]:
df1.dtypes

key           object
data_set_1     int32
dtype: object

In [54]:
df2.dtypes

key           object
data_set_2     int64
dtype: object

In [56]:
df1.set_index('key').join(df2.set_index('key'),how='inner')

data_set_1  data_set_2
key                        
Y             2           2
Z             1           3
Z             3           3

In [117]:
pd.merge(df1,df2) #inner join

key  data_set_1  data_set_2
0   Z           1           3
1   Z           3           3
2   Y           2           2

In [118]:
pd.merge(df1,df2,on='key')#inner join

key  data_set_1  data_set_2
0   Z           1           3
1   Z           3           3
2   Y           2           2

In [119]:
pd.merge(df1,df2,on='key',how='left')

key  data_set_1  data_set_2
0   X           0         NaN
1   Z           1         3.0
2   Y           2         2.0
3   Z           3         3.0
4   X           4         NaN
5   X           5         NaN

In [120]:
pd.merge(df1,df2,on='key',how='right')

key  data_set_1  data_set_2
0   Z         1.0           3
1   Z         3.0           3
2   Y         2.0           2
3   Q         NaN           1

In [121]:
pd.merge(df1,df2,on='key',how='outer')

key  data_set_1  data_set_2
0   X         0.0         NaN
1   X         4.0         NaN
2   X         5.0         NaN
3   Z         1.0         3.0
4   Z         3.0         3.0
5   Y         2.0         2.0
6   Q         NaN         1.0

In [59]:
df_left = pd.DataFrame({'key1': ['SF', 'SF', 'LA'],
                  'key2': ['one', 'two', 'one'],
                  'left_data': [10,20,30]})
df_right = pd.DataFrame({'key1': ['SF', 'SF', 'LA', 'LA'],
                   'key2': ['one', 'one', 'one', 'two'],
                   'right_data': [40,50,60,70]})

In [60]:
df_left

key1 key2  left_data
0   SF  one         10
1   SF  two         20
2   LA  one         30

In [61]:
df_right 

key1 key2  right_data
0   SF  one          40
1   SF  one          50
2   LA  one          60
3   LA  two          70

In [125]:
pd.merge(df_left, df_right, on=['key1', 'key2'], how='outer')

key1 key2  left_data  right_data
0   SF  one       10.0        40.0
1   SF  one       10.0        50.0
2   SF  two       20.0         NaN
3   LA  one       30.0        60.0
4   LA  two        NaN        70.0

In [126]:
pd.merge(df_left,df_right,on='key1')

key1 key2_x  left_data key2_y  right_data
0   SF    one         10    one          40
1   SF    one         10    one          50
2   SF    two         20    one          40
3   SF    two         20    one          50
4   LA    one         30    one          60
5   LA    one         30    two          70

In [127]:
pd.merge(df_left,df_right, on='key1',suffixes=('_lefty','_righty'))

key1 key2_lefty  left_data key2_righty  right_data
0   SF        one         10         one          40
1   SF        one         10         one          50
2   SF        two         20         one          40
3   SF        two         20         one          50
4   LA        one         30         one          60
5   LA        one         30         two          70

## Merge on Index

In [63]:
df_left = pd.DataFrame({'key': ['X','Y','Z','X','Y'],
                  'data': range(5)})
df_right = pd.DataFrame({'group_data': [10, 20]}, index=['X', 'Y'])

In [64]:
df_left

key  data
0   X     0
1   Y     1
2   Z     2
3   X     3
4   Y     4

In [65]:
df_right

group_data
X          10
Y          20

In [66]:
pd.merge(df_left,df_right,left_on='key',right_index=True)

key  data  group_data
0   X     0          10
3   X     3          10
1   Y     1          20
4   Y     4          20

In [131]:
pd.merge(df_left,df_right,left_on='key',right_index=True,how='outer')

key  data  group_data
0   X     0        10.0
3   X     3        10.0
1   Y     1        20.0
4   Y     4        20.0
2   Z     2         NaN

In [68]:
df_left_hr = pd.DataFrame({'key1': ['SF','SF','SF','LA','LA'],
                   'key2': [10, 20, 30, 20, 30],
                   'data_set': np.arange(5.)})
df_right_hr = pd.DataFrame(np.arange(10).reshape((5, 2)),
                   index=[['LA','LA','SF','SF','SF'],
                          [20, 10, 10, 10, 20]],
                   columns=['col_1', 'col_2'])

In [69]:
df_left_hr

key1  key2  data_set
0   SF    10       0.0
1   SF    20       1.0
2   SF    30       2.0
3   LA    20       3.0
4   LA    30       4.0

In [70]:
df_right_hr

col_1  col_2
LA 20      0      1
   10      2      3
SF 10      4      5
   10      6      7
   20      8      9

In [71]:
pd.merge(df_left_hr,df_right_hr,left_on=['key1','key2'],right_index=True)

key1  key2  data_set  col_1  col_2
0   SF    10       0.0      4      5
0   SF    10       0.0      6      7
1   SF    20       1.0      8      9
3   LA    20       3.0      0      1

In [72]:
pd.merge(df_left_hr,df_right_hr,left_on=['key1','key2'],right_index=True,how='outer')

key1  key2  data_set  col_1  col_2
0   SF    10       0.0    4.0    5.0
0   SF    10       0.0    6.0    7.0
1   SF    20       1.0    8.0    9.0
2   SF    30       2.0    NaN    NaN
3   LA    20       3.0    0.0    1.0
4   LA    30       4.0    NaN    NaN
4   LA    10       NaN    2.0    3.0

In [59]:
df_left.join(df_right)

key  data  group_data
0   X     0         NaN
1   Y     1         NaN
2   Z     2         NaN
3   X     3         NaN
4   Y     4         NaN

## GroupBy

In [88]:
df = pd.DataFrame({'k1':['X','X','Y','Y','Z'],
                    'k2':['alpha','alpha','alpha','beta','alpha'],
                    'dataset1':np.random.randn(5),
                    'dataset2':np.random.randn(5)})
df

k1     k2  dataset1  dataset2
0  X  alpha  1.272336 -0.367999
1  X  alpha  1.084514 -0.921329
2  Y  alpha -1.824543 -1.459295
3  Y   beta  0.199067  0.193992
4  Z  alpha  0.853669 -0.797162

In [ ]:
select count(empid) from table_name group by dept

In [82]:
df.groupby(df['k2']).mean()

dataset1  dataset2
k2                       
alpha  0.117272  0.027033
beta  -0.184292 -0.114877

In [89]:
df

k1     k2  dataset1  dataset2
0  X  alpha  1.272336 -0.367999
1  X  alpha  1.084514 -0.921329
2  Y  alpha -1.824543 -1.459295
3  Y   beta  0.199067  0.193992
4  Z  alpha  0.853669 -0.797162

In [100]:
(df.groupby(df['k2'])['dataset1'].sum()/df['dataset1'].sum())*100

k2
alpha    87.44089
beta     12.55911
Name: dataset1, dtype: float64

In [95]:
df['dataset1'].sum()

1.5850426232189103

In [110]:
df2=df.groupby(['k1','k2']).count()

In [111]:
df2

dataset1  dataset2
k1 k2                       
X  alpha         2         2
Y  alpha         1         1
   beta          1         1
Z  alpha         1         1

In [108]:
df1=df.groupby(['k1','k2']).count().reset_index()

In [109]:
df1

k1     k2  dataset1  dataset2
0  X  alpha         2         2
1  Y  alpha         1         1
2  Y   beta         1         1
3  Z  alpha         1         1

df1

In [75]:
group1 = df['dataset1'].groupby(df['k1'])
group1

In [76]:
group1.sum()

k1
X    1.203383
Y   -1.559302
Z    0.339152
Name: dataset1, dtype: float64

In [116]:
cities = np.array(['NY','LA','LA','NY','NY'])
month = np.array(['JAN','FEB','JAN','FEB','JAN'])

# Group the means by city and month
df['dataset1'].groupby([cities,month]).mean().reset_index()

level_0 level_1  dataset1
0      LA     FEB  1.084514
1      LA     JAN -1.824543
2      NY     FEB  0.199067
3      NY     JAN  1.063002

In [115]:
df.groupby(['k1','k2']).mean()['dataset2']

k1  k2   
X   alpha   -0.644664
Y   alpha   -1.459295
    beta     0.193992
Z   alpha   -0.797162
Name: dataset2, dtype: float64

In [146]:
df.groupby(['k1']).size()

k1
X    2
Y    2
Z    1
dtype: int64

In [117]:
group_dict = dict(list(df.groupby('k1')))
group_dict['X']

k1     k2  dataset1  dataset2
0  X  alpha  1.272336 -0.367999
1  X  alpha  1.084514 -0.921329

In [153]:
for k,v in group_dict.items():
    print(k)

X
Y
Z


In [118]:
dataset2_group = df.groupby(['k1','k2'])[['dataset2']]

dataset2_group.mean()

dataset2
k1 k2             
X  alpha -0.644664
Y  alpha -1.459295
   beta   0.193992
Z  alpha -0.797162

In [120]:
animals = pd.DataFrame(np.arange(16).reshape(4, 4),
                   columns=['W', 'X', 'Y', 'Z'],
                   index=['Dog', 'Cat', 'Bird', 'Mouse'])

animals

W   X   Y   Z
Dog     0   1   2   3
Cat     4   5   6   7
Bird    8   9  10  11
Mouse  12  13  14  15

In [121]:
#Now lets add some NAN values
animals.iloc[1:2, [1]] = np.nan 
animals

W     X   Y   Z
Dog     0   1.0   2   3
Cat     4   NaN   6   7
Bird    8   9.0  10  11
Mouse  12  13.0  14  15

In [122]:
behavior_map = {'W': 'good', 'X': 'bad', 'Y': 'good','Z': 'bad'}

In [123]:
animal_col = animals.groupby(behavior_map, axis=1)
animal_col

In [124]:
animal_col.sum()

bad  good
Dog     4.0   2.0
Cat     7.0  10.0
Bird   20.0  18.0
Mouse  28.0  26.0

In [165]:
behav_series = Series(behavior_map)
behav_series

W    good
X     bad
Y    good
Z     bad
dtype: object

In [170]:
for k,v in dict(list(animals.groupby(behav_series, axis=1))).items():
    print('Key: \n',k,'\nGroups: \n',v.head())

Key: 
 bad 
Groups: 
         X   Z
Dog     1   3
Cat     5   7
Bird    9  11
Mouse  13  15
Key: 
 good 
Groups: 
           W   Y
Dog     0.0   2
Cat     NaN   6
Bird    8.0  10
Mouse  12.0  14


In [172]:
animals.groupby(behav_series, axis=1).sum()

bad  good
Dog     4.0   2.0
Cat    12.0   6.0
Bird   20.0  18.0
Mouse  28.0  26.0

In [125]:
animals

W     X   Y   Z
Dog     0   1.0   2   3
Cat     4   NaN   6   7
Bird    8   9.0  10  11
Mouse  12  13.0  14  15

In [126]:
animals.groupby(len).sum()

W     X   Y   Z
3   4   1.0   8  10
4   8   9.0  10  11
5  12  13.0  14  15

In [128]:
keys = ['A', 'B', 'A', 'B']

animals.groupby([len, keys]).max().reset_index()

level_0 level_1   W     X   Y   Z
0        3       A   0   1.0   2   3
1        3       B   4   NaN   6   7
2        4       A   8   9.0  10  11
3        5       B  12  13.0  14  15